SEARCH(
    VARIABLE X SIZE(20) BOUNDED BY (10, 20) 
    MINIMIZE X**2
    CONSTRAINED BY (
        X[1] < X[2]   
    )
)
USING (
    POPULATION SIZE(30) INIT RANDOM WITH TOPOLOGY LBEST(5)
    ADD PARAMETERS (
         SELF_CONFIDANCE: AUTO(), --SUPPORT UNIFORM/NORMAL/... PARAMETER SETTING. INSPIRE FROM PYMC
         ... 
    )
    PARALLEL UPDATE ALL (  
       VELOCITY = SELF_CONFIDANCE*(BEST-POS)...
       POS = POS + VELOCITY  ...
    ) 
    PARALLEL UPDATE 3 WITH ROULETTE SELECTION (
       POS= BEST + POS ...
    )
    PARALLEL UPDATE 3 WITH RANDOM SELECTION (
       POS= BEST + POS ...
    ) WHERE IMPROVED --TO SPLIT PARAMETERS UPDATE FROM POS UPDATE? TO REPLACE FIT OR ONLY POS . R: POS IS THE AUXILIARY. PBEST IS THE REAL POS
) TUNE WITH ACO() --ACO, GE...TO FIND THINGS TO TUNE. OR SHOULD IT BE OUTSITE OF THE DSL. AT PYTHON LEVEL
UNTIL(
    EVALUATIONS(400)
)

_______________________________________________________

RETURNING *

--PARALLEL EXPERIMENTS: X to X time several population in paralel comunicate